In [104]:
%load_ext autoreload
%autoreload 1

import pandas as pd
import torch
import numpy as np
from argparse import Namespace
import os
import json

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm.notebook import tqdm
from torch.utils.data import Dataset
from sklearn.preprocessing import OneHotEncoder

from Dataset import JobDescriptionDataset
from Vectorizer import *


%aimport Dataset
%aimport Vectorizer


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Multiclass Classification

## Data Loading

In [105]:
task2 = pd.read_csv(f'./data/task2.csv')


In [124]:
class ElmanRNN(nn.Module):
    """ an Elman RNN built using the RNNCell """
    def __init__(self, input_size, hidden_size, batch_first=False):
        """
        Args:
            input_size (int): size of the input vectors
            hidden_size (int): size of the hidden state vectors
            bathc_first (bool): whether the 0th dimension is batch
        """
        super(ElmanRNN, self).__init__()
        
        self.rnn_cell = nn.RNNCell(input_size, hidden_size)
        
        self.batch_first = batch_first
        self.hidden_size = hidden_size

    def _initial_hidden(self, batch_size):
        return torch.zeros((batch_size, self.hidden_size))

    def forward(self, x_in, initial_hidden=None):
        """The forward pass of the ElmanRNN
        
        Args:
            x_in (torch.Tensor): an input data tensor. 
                If self.batch_first: x_in.shape = (batch, seq_size, feat_size)
                Else: x_in.shape = (seq_size, batch, feat_size)
            initial_hidden (torch.Tensor): the initial hidden state for the RNN
        Returns:
            hiddens (torch.Tensor): The outputs of the RNN at each time step. 
                If self.batch_first: hiddens.shape = (batch, seq_size, hidden_size)
                Else: hiddens.shape = (seq_size, batch, hidden_size)
        """
        if self.batch_first:
            batch_size, seq_size, feat_size = x_in.size()
            x_in = x_in.permute(1, 0, 2)
        else:
            seq_size, batch_size, feat_size = x_in.size()
    
        hiddens = []

        if initial_hidden is None:
            initial_hidden = self._initial_hidden(batch_size)
            initial_hidden = initial_hidden.to(x_in.device)

        hidden_t = initial_hidden
                   
        for t in range(seq_size):
            print(hidden_t)
            hidden_t = self.rnn_cell(x_in[t].float(), hidden_t.float())
            hiddens.append(hidden_t)
            
        hiddens = torch.stack(hiddens)

        if self.batch_first:
            hiddens = hiddens.permute(1, 0, 2)

        return hiddens



class RNNJobDescriptionClassifier(nn.Module):
    """ A Classifier with an RNN to extract features and an MLP to classify """
    def __init__(self, embedding_size, num_classes, rnn_hidden_size, batch_first=True, padding_idx=0):
        """
        Args:
            embedding_size (int): The size of the word embeddings
            num_embeddings (int): The number of words to embed
            num_classes (int): The size of the prediction vector 
                Note: the number of nationalities
            rnn_hidden_size (int): The size of the RNN's hidden state
            batch_first (bool): Informs whether the input tensors will 
                have batch or the sequence on the 0th dimension
            padding_idx (int): The index for the tensor padding; 
                see torch.nn.Embedding
        """
        super(RNNJobDescriptionClassifier, self).__init__()

        self.rnn = ElmanRNN(input_size=embedding_size,
                             hidden_size=rnn_hidden_size,
                             batch_first=batch_first)
        self.fc1 = nn.Linear(in_features=rnn_hidden_size,
                         out_features=rnn_hidden_size)
        self.fc2 = nn.Linear(in_features=rnn_hidden_size,
                          out_features=num_classes)

    def forward(self, x_in, x_lengths=None, apply_softmax=False):
        """The forward pass of the classifier
        
        Args:
            x_in (torch.Tensor): an input data tensor. 
                x_in.shape should be (batch, input_dim)
            x_lengths (torch.Tensor): the lengths of each sequence in the batch.
                They are used to find the final vector of each sequence
            apply_softmax (bool): a flag for the softmax activation
                should be false if used with the Cross Entropy losses
        Returns:
            the resulting tensor. tensor.shape should be (batch, output_dim)
        """
        y_out = self.rnn(x_in)

        if x_lengths is not None:
            y_out = column_gather(y_out, x_lengths)
        else:
            y_out = y_out[:, -1, :]

        y_out = F.relu(self.fc1(F.dropout(y_out, 0.5)))
        y_out = self.fc2(F.dropout(y_out, 0.5))

        if apply_softmax:
            y_out = F.softmax(y_out, dim=1)

        return y_out

In [125]:
def set_seed_everywhere(seed, cuda):
    np.random.seed(seed)
    torch.manual_seed(seed)
    if cuda:
        torch.cuda.manual_seed_all(seed)


args = Namespace(
    # Data and path information
    task="task2",
    model_state_file="model.pth",
    # Model hyper parameter
    word_embedding_size=8351,
    rnn_hidden_size=64,
    # Training hyper parameter
    num_epochs=5,
    learning_rate=1e-3,
    batch_size=64,
    seed=1337,
    early_stopping_criteria=5,
    # Runtime hyper parameter
    cuda=True,
    catch_keyboard_interrupt=True,
    reload_from_files=False,
    expand_filepaths_to_save_dir=True,

    vectorizer=OneHotVectoriser
)

# Check CUDA
if not torch.cuda.is_available():
    args.cuda = False
    
args.device = torch.device("cuda" if args.cuda else "cpu")
    
print("Using CUDA: {}".format(args.cuda))

set_seed_everywhere(args.seed, args.cuda)

Using CUDA: False


In [126]:
dataset = JobDescriptionDataset.load_dataset_and_make_vectorizer(args.task, 
                                                       args.vectorizer, 
                                                       "job_description", 
                                                       "category", 
                                                       True,
                                                       False)

In [127]:
def generate_batches(dataset, batch_size, shuffle=True, drop_last=True, device="cpu"):
    """
    A generator function which wraps the PyTorch DataLoader. It will
    ensure each tensor is on the write device location.
    """
    dataloader = DataLoader(dataset=dataset, batch_size=batch_size,
                            shuffle=shuffle, drop_last=drop_last)
    for data_dict in dataloader:
        out_data_dict = {}
        for name, tensor in data_dict.items():
            out_data_dict[name] = data_dict[name].to(device)
        yield out_data_dict
        
        

In [128]:
        
def make_train_state(args):
    return {'stop_early': False,
            'early_stopping_step': 0,
            'early_stopping_best_val': 1e8,
            'learning_rate': args.learning_rate,
            'epoch_index': 0,
            'train_loss': [],
            'train_acc': [],
            'val_loss': [],
            'val_acc': [],
            'test_loss': -1,
            'test_acc': -1,
            'model_filename': args.model_state_file}

def update_train_state(args, model, train_state):
    """Handle the training state updates.

    Components:
     - Early Stopping: Prevent overfitting.
     - Model Checkpoint: Model is saved if the model is better
    
    :param args: main arguments
    :param model: model to train
    :param train_state: a dictionary representing the training state values
    :returns:
        a new train_state
    """

    # Save one model at least
    if train_state['epoch_index'] == 0:
        torch.save(model.state_dict(), train_state['model_filename'])
        train_state['stop_early'] = False

    # Save model if performance improved
    elif train_state['epoch_index'] >= 1:
        loss_tm1, loss_t = train_state['val_loss'][-2:]
         
        # If loss worsened
        if loss_t >= loss_tm1:
            # Update step
            train_state['early_stopping_step'] += 1
        # Loss decreased
        else:
            # Save the best model
            if loss_t < train_state['early_stopping_best_val']:
                torch.save(model.state_dict(), train_state['model_filename'])
                train_state['early_stopping_best_val'] = loss_t

            # Reset early stopping step
            train_state['early_stopping_step'] = 0

        # Stop early ?
        train_state['stop_early'] = \
            train_state['early_stopping_step'] >= args.early_stopping_criteria

    return train_state


def compute_accuracy(y_pred, y_target):
    _, y_pred_indices = y_pred.max(dim=1)
    n_correct = torch.eq(y_pred_indices, y_target).sum().item()
    return n_correct / len(y_pred_indices) * 100

In [129]:
classifier = RNNJobDescriptionClassifier(embedding_size=args.word_embedding_size,
                               num_classes=len(dataset.get_vectorizer().class_vocab),
                               rnn_hidden_size=args.rnn_hidden_size)

In [130]:
loss_func = nn.CrossEntropyLoss(dataset.class_weights)
optimizer = optim.Adam(classifier.parameters(), lr=args.learning_rate)
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer=optimizer,
                                           mode='min', factor=0.5,
                                           patience=1)

train_state = make_train_state(args)

epoch_bar = tqdm(desc='training routine', 
                          total=args.num_epochs,
                          position=0)

dataset.set_split('train')
train_bar = tqdm(desc='split=train',
                          total=dataset.get_num_batches(args.batch_size), 
                          position=1, 
                          leave=True)
dataset.set_split('val')
val_bar = tqdm(desc='split=val',
                        total=dataset.get_num_batches(args.batch_size), 
                        position=1, 
                        leave=True)

training routine:   0%|          | 0/5 [00:00<?, ?it/s]

split=train:   0%|          | 0/270 [00:00<?, ?it/s]

split=val:   0%|          | 0/77 [00:00<?, ?it/s]

In [131]:
batch_generator = generate_batches(dataset, 
                                    batch_size=args.batch_size, 
                                           device=args.device)


In [132]:
try:
    for epoch_index in range(args.num_epochs):
        train_state['epoch_index'] = epoch_index

        # Iterate over training dataset

        # setup: batch generator, set loss and acc to 0, set train mode on
        dataset.set_split('train')
        batch_generator = generate_batches(dataset, 
                                           batch_size=args.batch_size, 
                                           device=args.device)
        running_loss = 0.0
        running_acc = 0.0
        classifier.train()

        for batch_index, batch_dict in enumerate(batch_generator):
            # the training routine is these 5 steps:

            # --------------------------------------    
            # step 1. zero the gradients
            optimizer.zero_grad()

            # step 2. compute the output
            y_pred = classifier(x_in=batch_dict['x_data'], 
                                x_lengths=batch_dict['x_length'])

            # step 3. compute the loss
            loss = loss_func(y_pred, batch_dict['y_target'])
    
            running_loss += (loss.item() - running_loss) / (batch_index + 1)

            # step 4. use loss to produce gradients
            loss.backward()

            # step 5. use optimizer to take gradient step
            optimizer.step()
            # -----------------------------------------
            # compute the accuracy
            acc_t = compute_accuracy(y_pred, batch_dict['y_target'])
            running_acc += (acc_t - running_acc) / (batch_index + 1)

            # update bar
            train_bar.set_postfix(loss=running_loss, acc=running_acc, epoch=epoch_index)
            train_bar.update()

        train_state['train_loss'].append(running_loss)
        train_state['train_acc'].append(running_acc)

        # Iterate over val dataset

        # setup: batch generator, set loss and acc to 0; set eval mode on

        dataset.set_split('val')
        batch_generator = generate_batches(dataset, 
                                           batch_size=args.batch_size, 
                                           device=args.device)
        running_loss = 0.
        running_acc = 0.
        classifier.eval()

        for batch_index, batch_dict in enumerate(batch_generator):
            # compute the output
            y_pred = classifier(x_in=batch_dict['x_data'], 
                                x_lengths=batch_dict['x_length'])

            # step 3. compute the loss
            loss = loss_func(y_pred, batch_dict['y_target'])
            running_loss += (loss.item() - running_loss) / (batch_index + 1)

            # compute the accuracy
            acc_t = compute_accuracy(y_pred, batch_dict['y_target'])
            running_acc += (acc_t - running_acc) / (batch_index + 1)
            val_bar.set_postfix(loss=running_loss, acc=running_acc, epoch=epoch_index)
            val_bar.update()

        train_state['val_loss'].append(running_loss)
        train_state['val_acc'].append(running_acc)

        train_state = update_train_state(args=args, model=classifier, 
                                         train_state=train_state)

        scheduler.step(train_state['val_loss'][-1])

        train_bar.n = 0
        val_bar.n = 0
        epoch_bar.update()

        if train_state['stop_early']:
            break
            
except KeyboardInterrupt:
    print("Exiting loop")

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])
tensor([[ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119],
        [ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119],
        [ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119],
        ...,
        [ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119],
        [ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119],
        [ 0.0253, -0.0148,  0.0482,  ...,  0.0131,  0.1342, -0.0119]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0684,  0.0168,  0.1626,  ...,  0.1208,  0.0260,  0.0962],
        [ 0.1397, -0.1243, -0.0624,  ...,  0.0665, -0.1016, -0.0200],
        [-0.0532, -0.1470,  0.0552,  ...,  0.0800,  0.0259, -0.0695],
        ...,
        [ 0.0926, -0.0711,  0.0417,  ...,  0.2259, -0.076

tensor([[ 0.0031,  0.0728,  0.0558,  ...,  0.0375,  0.1310,  0.0638],
        [ 0.0317, -0.0371,  0.2422,  ...,  0.1004, -0.0619, -0.1490],
        [-0.0590,  0.1029,  0.2565,  ...,  0.1917, -0.0678,  0.0947],
        ...,
        [ 0.1616,  0.1191,  0.1887,  ...,  0.3020, -0.1865,  0.1271],
        [ 0.0275,  0.0555,  0.2160,  ...,  0.1457,  0.0216, -0.1013],
        [-0.1195,  0.1770,  0.0505,  ...,  0.0477, -0.1024,  0.1044]],
       grad_fn=<TanhBackward0>)
tensor([[ 0.0551,  0.1242, -0.0016,  ...,  0.1601, -0.1925,  0.1218],
        [ 0.0983,  0.0521,  0.0351,  ...,  0.1367,  0.0493, -0.0411],
        [ 0.0154, -0.0296,  0.1141,  ...,  0.2291,  0.0581, -0.0656],
        ...,
        [-0.0032, -0.1046,  0.2722,  ...,  0.0160,  0.0465,  0.0415],
        [-0.0421, -0.0139,  0.0886,  ...,  0.1302, -0.0614,  0.0972],
        [-0.1882,  0.1551,  0.2580,  ...,  0.0060, -0.0325,  0.1416]],
       grad_fn=<TanhBackward0>)
tensor([[ 0.0727,  0.0287,  0.2182,  ...,  0.0938, -0.1174, -0.0195]

tensor([[ 0.0996,  0.0620,  0.0841,  ..., -0.0080, -0.1521, -0.1350],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0700,  0.1417,  ...,  0.0671, -0.0405,  0.0499],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0949,  0.1416,  0.1900,  ...,  0.1719, -0.0705, -0.0565]],
       grad_fn=<TanhBackward0>)
tensor([[-0.1394,  0.0963,  0.2215,  ...,  0.2046,  0.1755,  0.1252],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0906,  0.0701,  0.1417,  ...,  0.0670, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [ 0.0055,  0.0149,  0.2669,  ...,  0.0701, -0.0007,  0.0398]],
       grad_fn=<TanhBackward0>)
tensor([[ 0.1064,  0.0291,  0.0855,  ...,  0.2188, -0.1659, -0.0428]

tensor([[-0.0357,  0.0285,  0.1024,  ...,  0.3022,  0.0202,  0.0675],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0801, -0.1044,  0.2695,  ...,  0.1911, -0.0470, -0.0084],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[ 0.0758,  0.0500,  0.1087,  ...,  0.1142, -0.0984,  0.0369]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        ...,
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500],
        [-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]],
       grad_fn=<TanhBackward0>)
tensor([[-0.0907,  0.0701,  0.1417,  ...,  0.0671, -0.0404,  0.0500]

NameError: name 'column_gather' is not defined

## train_x = train.job_description
train_y = train.category.astype('category')

In [ ]:
train_y.unique()

# Models

## Vanilla RNN

NameError: name 'args' is not defined

### Interactive

In [77]:
interact(rnn_model_one_hot)

NameError: name 'interact' is not defined

In [78]:
interact(rnn_model_our_embeddings)

NameError: name 'interact' is not defined

In [79]:
interact(rnn_model_pretrained)

NameError: name 'interact' is not defined

## LSTM